Added additional button Add Current Page to https://backpack.tf/pricelist
mninc/gladiator.tf-bot-owner-script pull request #18
Opened 2024-08-14 13:52 UTC by GeorgiLazarov

Additional tests may be needed

2024-08-14 16:01 UTC, Moder112 requested changes
It looks good, thanks for the feature, there's only one minor nitpick

2024-08-14 16:01 UTC, Moder112 commented on gladiator.user.js
> +            return new Promise((resolve) => {
Minor nitpick, there's no asynchronous operations here so this doesn't need to be a promise

2024-08-16 17:08 UTC, ZeusJunior approved these changes

2024-08-30 08:49 UTC, Moder112 approved these changes

2024-08-30 08:50 UTC, Moder112 commented
Forgot about this PR, merging it now

2024-08-30 08:51 UTC, merged